version: '3.4'

services:
  redis: 
    ports:
      - "6379:6379"
  redis.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro